services:
    #######################################################
    db:
        image: postgres:15
        ports:
            - 5432:5432

        volumes:
            - postgres_data:/var/lib/postgresql/data/

        environment:
            - POSTGRES_DB=local
            - POSTGRES_PASSWORD=TestPassowrd
            - POSTGRES_USER=TestUser


    #######################################################
    web:
        build:
            context: .
            target: app
        image: api-app:latest

        env_file: .env

        ports:
            - 8000:8000

        volumes:
            - .:/code

        depends_on:
            - db
    

volumes:
    postgres_data: