"""initial schema

Revision ID: 215c9bc76bc7
Revises: 
Create Date: 2026-08-19 21:40:43.989723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql
import app.models.types
import sqlalchemy_utils.types.ltree

# revision identifiers, used by Alembic.
revision = '215c9bc76bc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS ltree')
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('USER', 'ADMIN', name='owner_type').create(op.get_bind())
    op.create_table('admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Admin accounts that manage the platform.'
    )
    op.create_index('idx_admin_email', 'admins', ['email'], unique=True)
    op.create_table('app_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_singleton', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('support_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Application-wide settings an admin can change without a deploy.'
    )
    op.create_index('idx_app_config_singleton', 'app_config', ['is_singleton'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path', sqlalchemy_utils.types.ltree.LtreeType(), nullable=False),
    sa.Column('grantable', sa.Boolean(), nullable=False),
    sa.Column('label', app.models.types.PydanticType(none_as_null=True, astext_type=Text()), nullable=False),
    sa.Column('description', app.models.types.PydanticType(none_as_null=True, astext_type=Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'grantable', name='uq_permission_id_grantable'),
    comment='Seeded tree of admin permissions.'
    )
    op.create_index('idx_permission_path', 'permissions', ['path'], unique=True)
    op.create_index('idx_permission_path_gist', 'permissions', ['path'], unique=False, postgresql_using='gist')
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_type', postgresql.ENUM('USER', 'ADMIN', name='owner_type', create_type=False), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_owner_id'), 'sessions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_sessions_owner_type'), 'sessions', ['owner_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='User accounts.'
    )
    op.create_index('idx_user_email', 'users', ['email'], unique=True)
    op.create_index('idx_user_first_name', 'users', ['first_name'], unique=False)
    op.create_index('idx_user_last_name', 'users', ['last_name'], unique=False)
    op.create_table('admin_permissions',
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('grantable', sa.Boolean(), sa.Computed('true', persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id', 'grantable'], ['permissions.id', 'permissions.grantable'], name='fk_admin_permission_grantable', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('admin_id', 'permission_id'),
    comment='Permissions granted to each admin.'
    )
    op.create_index('idx_admin_permission_permission_id', 'admin_permissions', ['permission_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('media', app.models.types.PydanticListType(none_as_null=True, astext_type=Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Posts published by users.'
    )
    op.create_index('idx_post_created_at', 'posts', ['created_at'], unique=False)
    op.create_index('idx_post_user_id', 'posts', ['user_id'], unique=False)
    op.create_table('saved_posts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id'),
    comment='Posts a user saved.'
    )
    op.create_index('idx_saved_post_post_id', 'saved_posts', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_saved_post_post_id', table_name='saved_posts')
    op.drop_table('saved_posts')
    op.drop_index('idx_post_user_id', table_name='posts')
    op.drop_index('idx_post_created_at', table_name='posts')
    op.drop_table('posts')
    op.drop_index('idx_admin_permission_permission_id', table_name='admin_permissions')
    op.drop_table('admin_permissions')
    op.drop_index('idx_user_last_name', table_name='users')
    op.drop_index('idx_user_first_name', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sessions_owner_type'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_owner_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_permission_path_gist', table_name='permissions', postgresql_using='gist')
    op.drop_index('idx_permission_path', table_name='permissions')
    op.drop_table('permissions')
    op.drop_index('idx_app_config_singleton', table_name='app_config')
    op.drop_table('app_config')
    op.drop_index('idx_admin_email', table_name='admins')
    op.drop_table('admins')
    sa.Enum('USER', 'ADMIN', name='owner_type').drop(op.get_bind())
    # ### end Alembic commands ###
    op.execute('DROP EXTENSION IF EXISTS ltree')
